export enum TypeAdmin {
    SUPER_ADMIN = 'SUPER_ADMIN',
    SCOLARITE = 'SCOLARITE',
    CHEF_DEPARTEMENT = 'CHEF_DEPARTEMENT',
    DIRECTEUR_ADGJOINTE = 'DIRECTEUR_ADGJOINTE',
    SECRETAIRE_GENERALE = 'SECRETAIRE_GENERALE',
}